### ISSUE TITLE
Unsuitable Method for URL (Spring Boot 3.3.2 and Flyway)

### ISSUE THREAD

**Issue by crgardner** [gavlyukovskiy/spring-boot-data-source-decorator#100]
I'm using the following dependencies for a multi-module maven project

datasource-proxy-spring-boot-starter - 1.9.1
Java 21
Spring Boot 3.3.2 (also tried with 3.3.1)
Postgres DB
Flyway

When I start the application, I receive the following exception. I don't have the problem when not using datasource-proxy-spring-boot-starter. 

Caused by: org.springframework.boot.jdbc.UnsupportedDataSourcePropertyException: Unable to find suitable method for url
	at org.springframework.boot.jdbc.UnsupportedDataSourcePropertyException.throwIf(UnsupportedDataSourcePropertyException.java:36) ~[spring-boot-3.3.2.jar:3.3.2]
	at org.springframework.boot.jdbc.DataSourceBuilder$ReflectionDataSourceProperties.getMethod(DataSourceBuilder.java:580) ~[spring-boot-3.3.2.jar:3.3.2]
	at org.springframework.boot.jdbc.DataSourceBuilder$ReflectionDataSourceProperties.get(DataSourceBuilder.java:570) ~[spring-boot-3.3.2.jar:3.3.2]
	at org.springframework.boot.jdbc.DataSourceBuilder.build(DataSourceBuilder.java:180) ~[spring-boot-3.3.2.jar:3.3.2]
	at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.getMigrationDataSource(FlywayAutoConfiguration.java:205) ~[spring-boot-autoconfigure-3.3.2.jar:3.3.2]
	at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.configureDataSource(FlywayAutoConfiguration.java:184) ~[spring-boot-autoconfigure-3.3.2.jar:3.3.2]
	at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.flyway(FlywayAutoConfiguration.java:172) ~[spring-boot-autoconfigure-3.3.2.jar:3.3.2]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146) ~[spring-beans-6.1.11.jar:6.1.11]

**Comment by gavlyukovskiy** [comment]
@crgardner fixed in 1.9.2
